version: '3.2'

services:

  ns_support_app: &app
    tty: true
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: ns_support
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev

  test:
    <<: *app
    container_name: ns_support_test
    ports:
      - 8082:8082
    entrypoint: py.test -v -p no:warnings
    command: ''
