# Generated by Django 3.2.3 on 2021-05-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsdispatch',
            name='dispatch_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nsdispatch',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nsdispatch',
            name='subcategory',
            field=models.IntegerField(default=0),
        ),
    ]
