# Generated by Django 3.2.3 on 2021-05-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_auto_20210515_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NSDispatch',
        ),
    ]
