# Generated by Django 3.2.3 on 2021-05-15 22:08

import comms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comms', '0003_delete_nsdispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(verbose_name='dispatch_text')),
                ('dispatch_id', models.IntegerField(default=0)),
                ('category', models.IntegerField(default=0)),
                ('subcategory', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(comms.models.NSDispatchStatus['PREPARE'], 'Prepare'), (comms.models.NSDispatchStatus['COMPLETE'], 'Complete'), (comms.models.NSDispatchStatus['DELETE'], 'Deleted')], max_length=15)),
            ],
        ),
    ]
